checks:
  php: true

tools:
  external_code_coverage:
    runs: 6    # Scrutinizer will wait for 6 code coverage submissions
    timeout: 600    # Timeout in seconds.

filter:
  excluded_paths:
    - 'features/'
    - 'tests/'

build:
  environment:
    # Languages
    php:
      version: "7.4"

  dependencies:
    override:
      - composer update --no-interaction --no-scripts --ignore-platform-reqs

  tests:
    override:
      - php-scrutinizer-run
