checks:
  php: true

tools:
  external_code_coverage:
    runs: 2    # Scrutinizer will wait for two code coverage submissions

filter:
  excluded_paths:
    - 'features/'
    - 'tests/'

build:
  environment:
    # Languages
    php:
      version: "7.1"

  tests:
    override:
      -
        command: 'vendor/bin/phpunit --coverage-clover=build/phpunit.clover'
        coverage:
            file: 'build/phpunit.clover'
            format: 'clover'
      - php-scrutinizer-run
