checks:
  php: true

tools:
  external_code_coverage:
    runs: 2    # Scrutinizer will wait for two code coverage submissions

filter:
  excluded_paths:
    - 'features/'
    - 'tests/'

build:
  environment:
    # Languages
    php:
      version: "7.4"

  tests:
    override:
      - php-scrutinizer-run
